# Day1_ass3

In [1]:
import numpy as np

In [2]:
array = np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
array = np.ones(10)
print("An array of 10 ones:")
print(array)

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
array = np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [7]:
array = np.ones(10)*10
print("An array of 10 tens:")
print(array)

An array of 10 tens:
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [8]:
array = np.ones(10)*20
print("An array of 10 twentys:")
print(array)

An array of 10 twentys:
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


In [9]:
array = np.ones(10)*50
print("An array of 10 fiftys:")
print(array)

An array of 10 fiftys:
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]
