# Day1_ass17

In [1]:
import numpy as np

In [2]:
X = np.random.random((2,3,4))
print(X)

[[[0.65653823 0.30727445 0.6344571  0.01479816]
  [0.88684602 0.82190477 0.684822   0.52622694]
  [0.92868738 0.71366792 0.99084544 0.85088321]]

 [[0.87033963 0.33428016 0.76445275 0.36784043]
  [0.51252969 0.3454227  0.40932462 0.49120634]
  [0.56257734 0.18565675 0.19240122 0.99842894]]]
