# Day1_ass16

In [2]:
import numpy as np

In [3]:
X = np.random.random((3,3,3,))
print(X)

[[[0.59758199 0.99133456 0.16835235]
  [0.52754778 0.58084113 0.31748989]
  [0.84992667 0.01585192 0.80251197]]

 [[0.6403205  0.62218701 0.87244311]
  [0.99917524 0.10463389 0.86271396]
  [0.0442663  0.45208291 0.2088236 ]]

 [[0.85397581 0.27363646 0.76126749]
  [0.12532862 0.79681325 0.52530394]
  [0.51543823 0.82963407 0.50410304]]]
